# encoding: utf-8
module Controladorqytetet
		OpcionMenu = [:INICIARJUEGO, :JUGAR, :APLICARSORPRESA,
		:INTENTARSALIRCARCELPAGANDOLIBERTAD, :INTENTARSALIRCARCELTIRANDODADO,
		:COMPRARTITULOPROPIEDAD, :HIPOTECARPROPIEDAD, :CANCELARHIPOTECA,
		:EDIFICARCASA, :EDIFICARHOTEL, :VENDERPROPIEDAD, :PASARTURNO,
		:OBTENERRANKING, :TERMINARJUEGO, :MOSTRARJUGADORACTUAL,
		:MOSTRARJUGADORES, :MOSTRARTABLERO]
end